Add a frozen mode to update configuration
sbt/librarymanagement pull request #100
Opened 2017-05-11 16:06 UTC by jvican

The frozen mode is used by the dependency lock file.

It makes sure that the resolution is always intransitive and that ivy
does not check for changed dependencies and stores that information in
the resolved ivy files. Following the ivy documentation, the last change
may bring a slight performance improvement:

http://ant.apache.org/ivy/history/latest-milestone/use/resolve.html

2017-05-11 16:07 UTC, jvican commented
Review by @eed3si9n.

2017-05-11 16:17 UTC, jvican commented
This is passing and give us pretty good performance results. It's more than 2x faster.
  
From the CI, we get these results:
* Normal resolution: `:: resolution report :: resolve 185ms :: artifacts dl 1961ms`.
* Frozen resolution: `:: resolution report :: resolve 76ms :: artifacts dl 1635ms`.
  
Yay.

2017-05-12 12:07 UTC, jvican commented
ping @eed3si9n

2017-05-12 16:01 UTC, eed3si9n requested changes
I think the general direction is fine, but I'm not sure about the term "frozen." As seen in the debate around eviction warning, I think we should try to stick to some terms that are standard.
Would it make sense to call it "locked" mode?

2017-05-12 16:05 UTC, jvican commented
@eed3si9n Frozen resolution is the term used by Pants. I think it's the clearest one, since "locked" could mean something else. To me, frozen describes the fact that all dependencies are frozen (no transitive resolution will happen) and that artifacts are not supposed to change those transitive dependencies (that's why `checkDeps` is disabled.

2017-05-12 16:32 UTC, eed3si9n commented
The only reference I could find was the source code (https://github.com/pantsbuild/pants/blob/master/src/python/pants/backend/jvm/ivy_utils.py). Is there a page where it is explained?

2017-05-12 16:34 UTC, jvican commented
Yes, [here](https://rbcommons.com/s/twitter/r/3555/diff/6#index_header).

2017-05-12 16:43 UTC, eed3si9n approved these changes

2017-05-12 16:43 UTC, merged