Add missing CrossVersion.disabled
sbt/librarymanagement pull request #103
Opened 2017-05-18 02:03 UTC by cunei

2017-05-18 04:59 UTC, eed3si9n commented
I want to clarify that this is "missing" in the sense of consistency, but not missing from migration from sbt 0.13, correct? `def full` was there because `Full(...)` used to wrap a function.

https://github.com/sbt/sbt-zero-thirteen/blob/596702f9297b364ef0f77b01758362875d975488/ivy/src/main/scala/sbt/CrossVersion.scala

2017-05-18 14:58 UTC, cunei commented
The Full/Binary/Disabled classes and objects moved with the switch to Contraband: they used to live under CrossVersion, and now are directly in sbt.librarymanagement.xxx. Since Disabled did not have an associated `disabled` method, what used to be CrossVersion.Disabled (and not CrossVersion.disabled) can now only be referred to as `sbt.librarymanagement.Disabled()`. If people used CrossVersion.Disable, that is going to break in any case when upgrading. Therefore, it makes sense to offer at least a CrossVersion.disabled, for consistency with the others (.full, .binary, etc).

2017-05-18 15:05 UTC, eed3si9n commented
ok. So should we also add `.disabled` to sbt 0.13.x so someone can cross build?

2017-05-18 15:08 UTC, eed3si9n approved these changes

2017-05-18 15:18 UTC, cunei commented
I think so; either that, or adding a CrossVersion.Disabled to 1.0.

2017-05-18 15:29 UTC, eed3si9n commented
Yea. Let's do that.

Could you add `def Disabled: CrossVersion = sbt.librarymanagement.Disabled()` in addition?

2017-05-18 15:42 UTC, dwijnand commented
Could you make it a val and not deprecated so it can be in pattern matching, please?

* https://github.com/sbt/sbt/commit/7fcfec8b8e2b58b33b028606ecafc8ae03f7cdd4#diff-d6dcabccfa076d9f9b74ace121e616d0L72
* https://github.com/scala-js/scala-js/compare/master...dwijnand:sbt1?expand=1#diff-44651170054d48e2ec5d9afe83219da5R38

2017-05-18 15:47 UTC, cunei commented
As things stand, pattern matching will certainly break for some people, considering that CrossVersion.Full, CrossVersion.Binary, etc do not exist any longer. A better solution would be to add aliases to all of them within CrossVersion, pointing to the new locations. Maybe using `type` ?

2017-05-18 15:53 UTC, dwijnand commented
Yeah the migration to Contraband maimed the migration.

I agree to adding both type and val aliases for Full/Binary/Disabled to avoid unnecessary differences.

2017-05-18 18:07 UTC, dwijnand requested changes

2017-05-18 18:07 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/CrossVersionExtra.scala
> +  val Patch: CrossVersion = patch
These must be of the target's type, not CrossVersion, to function with pattern matching:

```scala
val Disabled  = sbt.Disabled
val Binary    = sbt.Binary
val Full      = sbt.Full
val Patch     = sbt.Patch
type Binary   = sbt.Binary
type Full     = sbt.Full
type Patch    = sbt.Patch
```

2017-05-18 18:07 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/CrossVersionExtra.scala
> +  type Disabled = LDisabled
There is no type `sbt.CrossVersion.Disabled` in sbt 0.13. There is only the singleton type `sbt.CrossVersion.Disabled.type`.

2017-06-28 13:31 UTC, dwijnand commented
@cunei Would you like me to finish this off?

2017-06-29 13:25 UTC, cunei commented
@dwijnand Yes, please go ahead; I'll be stuck on dbuild for another while. Thanks.

2017-06-30 13:57 UTC, dwijnand commented
Superseded by #121.

2017-06-30 13:57 UTC, closed without merging