Implement `managedChecksums` in ivy
sbt/librarymanagement pull request #105
Opened 2017-05-26 10:20 UTC by jvican

Managed checksums tells ivy to forget about checking checksums for jar
files and just persist them in the cache.

The user that enables that option will take care of verifying they are
correct.

This is a big deal because:
  
1. Ivy takes *a lot of time* checking timestamps for big jars, and does it
sequentially. The user (sbt) can do better by running these checks in parallel,
speeding up the whole resolution process!
2. The fact that the sha files are not present in the cache means that build
tools cannot check if a checksum is correct without preprocessing the jar.

Note that the user is responsible for keeping the cache consistent. If the
checksum is not correct, the user should report it and overwrite the
checksum file with the valid digest.

2017-05-26 10:21 UTC, jvican commented
Review by @eed3si9n.

2017-05-26 10:22 UTC, jvican commented
I forgot to mention that this also adds a field `checksum` to `ModuleID`, which is super useful for the dependency lock file and for those users that want to explicitly say what the checksum a module is (a la Pants).

2017-05-26 13:00 UTC, jvican commented
Tests are green.

2017-05-26 19:14 UTC, eed3si9n requested changes
As noted in the Gitter chat, a better optimization around checksum is to utilize HTTP headers when available (Maven Central provides `X-Checksum-SHA1`).

Also ModuleID is not the right place, I think.

2017-05-26 19:14 UTC, eed3si9n commented on librarymanagement/src/main/contraband/librarymanagement.json
> +        { "name": "checksum",          "type": "Option[sbt.librarymanagement.Checksum]", "default": "None",                             "since": "0.0.1" }
I think this is at a wrong layer. First, a module may consist of many artifacts.
Second, it's an addressing mechanism, so you won't know the checksum up front.

2017-05-27 21:56 UTC, eed3si9n approved these changes

2017-05-27 22:01 UTC, merged

2017-05-27 22:02 UTC, eed3si9n commented
Merged! Thanks for the contribution.

2017-05-27 22:02 UTC, jvican commented
I have just opened an issue to keep track of your suggestion: https://github.com/sbt/librarymanagement/issues/108.