define def config(...) as a macro to capture the Scala identifier
sbt/librarymanagement pull request #113
Opened 2017-06-10 08:21 UTC by eed3si9n

In preparation to forward porting https://github.com/sbt/sbt/pull/3255, this change the implementation of `def config(name: String)` so it captures the LHS as the `id` field in Configuration.
The constructor now enforces that the `id` (the Scala identifier for val) starts with upper case, like `Compile` and `Test`.

2017-06-12 09:20 UTC, jvican commented
Please, don't merge this. I'd like to review this PR soon and want to think a little bit about this change.

2017-07-06 10:42 UTC, eed3si9n commented
I we've agreed on eventual adoption of slash syntax, can I merge this soon?

2017-07-06 10:52 UTC, jvican commented
I think this is good to go, sorry for blocking. I think enforcing this in the slash syntax is key for its well-functioning.

2017-07-06 11:00 UTC, dwijnand requested changes

2017-07-06 11:00 UTC, dwijnand commented on librarymanagement/src/main/contraband/librarymanagement.json
> +        { "name": "configurations",  "type": "String*",                              "default": "Vector.empty",              "since": "0.0.1" },
Please can we not make this change? This could be `ConfigKey`, or similar.

2017-07-06 11:02 UTC, eed3si9n commented on librarymanagement/src/main/contraband/librarymanagement.json
> +        { "name": "configurations",  "type": "String*",                              "default": "Vector.empty",              "since": "0.0.1" },
Yea. I think it would be good to introduce ConfigRef in this PR.

2017-07-06 11:05 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/ConfigurationExtra.scala
> +      .map(_.tree.asInstanceOf[c.Tree])
It's a shame to have this code copy-pasted from sbt's KeyMacro :-/

2017-07-06 11:06 UTC, eed3si9n commented on librarymanagement/src/main/scala/sbt/librarymanagement/ConfigurationExtra.scala
> +      .map(_.tree.asInstanceOf[c.Tree])
Would you rather have me add util-lhs?

2017-07-06 11:07 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/ConfigurationExtra.scala
> +      .map(_.tree.asInstanceOf[c.Tree])
(┛◉Д◉)┛彡┻━┻

😃

2017-07-08 13:02 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/113/head&deploy_to_bintray=false">this link.</A>

2017-07-08 13:04 UTC, eed3si9n commented
Rebased to 1.0 and added ConfigRef.

2017-07-08 14:10 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/113/head&deploy_to_bintray=false">this link.</A>

2017-07-08 16:07 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/ConfigurationFormats.scala
> + * This code is generated using [[http://www.scala-sbt.org/contraband/ sbt-contraband]].
Why is this not in the `contraband-scala` directory?

2017-07-08 16:10 UTC, eed3si9n commented on librarymanagement/src/main/scala/sbt/librarymanagement/Configuration.scala
> +final class Configuration private[sbt] (
@dwijnand The ctor for Configuration is private.

2017-07-09 03:54 UTC, eed3si9n commented
Can we merge this so the review surface will be smaller for the API PR?

2017-07-10 09:02 UTC, dwijnand approved these changes

2017-07-10 09:02 UTC, merged