In-source the modules of sbt/util required in sbt/lm
sbt/librarymanagement pull request #118
Opened 2017-06-26 09:25 UTC by dwijnand

The subset of sbt/util was prepared like this:

1. Move sbt.internal.util.HListFormats from util-cache to util-collection
(which isn't include here) to break the dependency between util-cache and
util-collection.

2. Move sbt.util.ShowLines out of util-collection to its own dependency to
break the dependency of util-logging on util-collection.

3. Move sbt.internal.util.Position out of util-collection to its own dependency
to break the dependency of lm on util-collection.

4. Run git filter-branch as such:

    cd /s
    git clone /d/sbt-util /d/sbt-util-4-lm
    git filter-branch --index-filter \
      'git rm --cached -qr -- . && git reset -q $GIT_COMMIT -- interface internal/util-interface util/log internal/util-logging internal/util-position internal/util-showlines cache internal/util-cache util-cache' \
      --prune-empty
    git reset --hard
    git gc --aggressive
    git prune

Then that branch was merged into the 'eat-util' branch here, the build was
configured, and the source auto-formatted.

2017-06-28 14:08 UTC, eed3si9n requested changes

2017-06-28 14:08 UTC, eed3si9n commented on build.sbt
> +  name := "LM Interface",
I don't know if the name LM Interface or LM Logging makes sense, since it really isn't about library management.

2017-06-28 14:15 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/118/head&deploy_to_bintray=false">THIS LINK.</A>

2017-06-30 11:20 UTC, dwijnand commented
See https://github.com/sbt/util/issues/58#issuecomment-312242348.

2017-06-30 11:20 UTC, closed without merging