[wip] starting library management API
sbt/librarymanagement pull request #123
Opened 2017-07-02 11:10 UTC by eed3si9n

Thus far I've split core interface from ivy-dependent parts, which drives towards non-ivy based implementation of this API.

2017-07-02 11:10 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 04:51 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 05:49 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 06:05 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 06:13 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 07:41 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 08:25 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 08:50 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 10:46 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 11:33 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-03 12:04 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/123/head&deploy_to_bintray=false">this link.</A>

2017-07-04 09:46 UTC, eed3si9n commented
Note to self https://github.com/sbt/sbt/issues/2088#issuecomment-246208872

2017-07-04 19:30 UTC, eed3si9n commented
I had conversation with @dwijnand this morning, one of the suggestions he had was avoid inheritance between LibraryMangement and LibraryManagementInterface, and use composition.

2017-07-05 09:12 UTC, dwijnand commented on core/src/main/contraband-scala/sbt/librarymanagement/DeliverConfiguration.scala
> +  val configurations: Option[scala.Vector[String]],
Could we introduce a `ConfigRef` (or similar) type, so these aren't just bare, indistinguishable strings?

2017-07-05 09:12 UTC, dwijnand commented on ivy/src/main/contraband-scala/sbt/librarymanagement/LibraryManagementCodec.scala
> +trait LibraryManagementCodec extends sbt.internal.librarymanagement.formats.GlobalLockFormat
This is a duplicate `sbt.librarymanagement.LibraryManagementCodec`. Should be moved or elided.

2017-07-05 10:26 UTC, Duhemm requested changes
That's super exciting!

Given that it's going to be sbt's official library management API, I think that we should put some extra effort to documentation and making sure that we don't expose stuff that are not necessary. I'd be happy to help with that.

Could you maybe move your branch to this repository? This would allow other people to open PR against your branch while keeping the history here.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/internal/librarymanagement/JsonUtil.scala
> +// import core.module.descriptor.ModuleDescriptor
We can get rid of commented out code.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/internal/librarymanagement/JsonUtil.scala
> +      // md: ModuleDescriptor,
Same here

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/internal/librarymanagement/formats/DependencyResolverFormat.scala
> +// }
This file can be removed.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +    dummyModule(dependencyId, None)
I'm not 100% sure that's the best name we could come up with. IIRC, that's the name I gave it in zinc when doing the compiler bridge stuff because it was private. It's called `wrapDependencyInModule` in Zinc now, I think that's much better.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +    buildModule(moduleId, directDependencies, scalaModuleInfo, Vector(Configurations.Component))
When I read `buildModule` I'm thinking about a global `ModuleDescriptor` for the whole build, but it's actually the `ModuleDescriptor` for one project. What do you think about calling this method `moduleDescriptor`, or maybe `projectModule`?

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +    retrieveEither(dummyModule(dependencyId, scalaModuleInfo), retrieveDirectory, log)
How about simply `retrieve`? The `Either` part of the name is already In the type signature. Moreover, we don't have unsafe variants of this.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +    // Using the default artifact type filter here, so sources and docs are excluded.
Do we want to make that configurable? Maybe it could include a parameter for `missingOk` too.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +  def transitiveScratch(
What does this do? Should it be part of the public LM API?

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +  def transitiveScratch(
I think that it's only used in sbt/sbt for `updateSbtClassifiers`.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +    buildModule(moduleId, directDependencies, scalaModuleInfo, Vector(Configurations.Component))
The doc should say that it sets the `Component` configuration.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +abstract class LibraryManagement extends LibraryManagementInterface {
That's going to be the entry point for any body that will use the API, so we should maybe put some extra effort in the javadoc and add all the `@param` etc.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +  def updateClassifiersEither(
I don't really get what this method do based on the doc.

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +        // FIXME: this is only done because IDE plugins depend on `classifier` to determine type. They
There's a trailing `They` at the end of the comment?

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +  protected def dependenciesNames(module: ModuleDescriptor): String =
`directDependenciesNames` to avoid surprises, maybe?

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +object LibraryManagementInterface
Why do we need this object?

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +  def directDependenciesForWarning: Vector[ModuleID]
Why `ForWarning`?

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/MakePomConfiguration.scala
> +// )
Commented out code

2017-07-05 10:26 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/MakePomConfiguration.scala
> +    val filterRepositories: MavenRepository => Boolean = _ => true,
Is it an inclusion or exclusion filter? I think this class could benefit from some more documentation.

2017-07-05 10:51 UTC, eed3si9n commented
Closing this PR to move the branch to `topic/api` per @Duhemm's comment above.

2017-07-05 11:02 UTC, closed without merging