Library management API
sbt/librarymanagement pull request #124
Opened 2017-07-05 10:48 UTC by eed3si9n

This is continuation of https://github.com/sbt/librarymanagement/pull/123 on a shared branch.

Ref https://github.com/sbt/sbt/issues/2294

The goal of Library Management API is to create an Ivy-free interface that can abstract different dependency resolution implementations such as Ivy, cached resolution, and Coursier.

Note this PR is intended to be Refactoring, in the sense that this should not introduce any change to the observable behavior.

### LibraryManagementInterface

This interface is for the dependency resolution engine authors:

```scala
/**
 * Interface for library management
 */
abstract class LibraryManagementInterface {

  /**
   * Builds a ModuleDescriptor that describes a subproject with dependencies.
   *
   * @param moduleSetting It contains the information about the module including the dependencies.
   */
  def buildModule(moduleSetting: InlineConfiguration): ModuleDescriptor

  /**
   * Resolves the given module's dependencies performing a retrieval.
   *
   * @param module The module to be resolved.
   * @param configuration The update configuration.
   * @param uwconfig The configuration to handle unresolved warnings.
   * @param log The logger.
   * @return The result, either an unresolved warning or an update report. Note that this
   *         update report will or will not be successful depending on the `missingOk` option.
   */
  def updateEither(module: ModuleDescriptor,
                   configuration: UpdateConfiguration,
                   uwconfig: UnresolvedWarningConfiguration,
                   log: Logger): Either[UnresolvedWarning, UpdateReport]

  /**
   * Publishes the given module.
   *
   * @param module The module to be resolved.
   * @param configuration The publish configuration.
   * @param log The logger.
   */
  def publish(module: ModuleDescriptor, configuration: PublishConfiguration, log: Logger): Unit

  /**
   * Makes the .ivy file for the given module.
   *
   * @param module The module to be resolved.
   * @param configuration The makeIvyFile configuration.
   * @param log The logger.
   */
  def makeIvyFile(module: ModuleDescriptor, configuration: DeliverConfiguration, log: Logger): File

  /**
   * Makes the .pom file for the given module.
   *
   * @param module The module to be resolved.
   * @param configuration The makeIvyFile configuration.
   * @param log The logger.
   */
  def makePomFile(module: ModuleDescriptor, configuration: MakePomConfiguration, log: Logger): File
}

trait ModuleDescriptor {
  def directDependenciesForWarning: Vector[ModuleID]
  def scalaModuleInfo: Option[ScalaModuleInfo]
}
```

These methods define the most general forms of performing `update` and `publish`.
If the implementation already integrates with sbt, it should be easy to implement them.

### LibraryMangement

`LibraryMangement` is an extension of `LibraryManagementInterface` that contains other useful helper functions. This is intended for the consumers of this API.

https://github.com/eed3si9n/librarymanagement/blob/7b21353a06aab419de7892fd13cee2f4da8f26da/core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala

### IvyLibraryManagement

Here's the reference implementation using Ivy.

https://github.com/eed3si9n/librarymanagement/blob/7b21353a06aab419de7892fd13cee2f4da8f26da/ivy/src/main/scala/sbt/librarymanagement/IvyLibraryManagement.scala

2017-07-05 10:49 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-06 12:05 UTC, Duhemm commented
Note: I've already started to port sbt/zinc to the new LM API described in this PR.

2017-07-08 14:28 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-08 17:02 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-08 17:30 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-08 19:18 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-10 12:38 UTC, Duhemm commented
I've created a gist that shows how to resolve a given module ID with this API:
https://gist.github.com/Duhemm/0b2a6a7bd198abfda36f5412d49bdaf9

I think that there's still room for improvement. Here are some notes that I took while writing that:

 - `IvyConfiguration` is in `sbt.internal`, but we need it to use this API with Ivy.
 - `InlineIvyConfiguration` should also follow the builder pattern, and it requires some sane defaults. Maybe that we could also come up with a better name...
 - `IvyConfiguration` uses a logger, do we really need to give another one to `retrieve`? Can't it use the logger of its `LibraryManagement` instance? Does `IvyConfiguration` really need a logger?
 - `IvyPaths` is in `sbt.internal`, but we need it to instantiate `IvyConfiguration`.
 - Both `IvyPaths` and `IvyConfiguration` need a `BaseDirectory`. Couldn't they share the same?
 - We can get defaults resolvers using `Resolver.withDefaultResolvers`. I think that we should drop the `with` from the name.
 - `Resolver.withDefaultResolvers` returns a `Seq`, but `InlineIvyConfiguration` wants a `Vector`.
 - Why isn't there a way to set the configuration on an instance of `ModuleDescriptor`?
 - `def moduleDescriptor` takes a `Vector[Configuration]`, but `ModuleID` takes `Option[String]`.
 - In [this gist](https://gist.github.com/Duhemm/0b2a6a7bd198abfda36f5412d49bdaf9#file-libman-scala-L44), I need to set the configurations on the `ModuleID` to `component`. Any other configuration will fail. That's extremely confusing.

That would be great if we could get this example to become shorter.

2017-07-10 13:14 UTC, Duhemm commented
I guess we should move everything that's specific to the Ivy implementation to the `sbt.librarymanagement.ivy` namespace. WDYT?

2017-07-10 21:52 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 10:05 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 10:08 UTC, eed3si9n commented
@Duhemm Here's my take on the builder pattern - https://github.com/sbt/librarymanagement/pull/124/commits/e077272df2ec1e6acf7331f867e1794a4a7628f9

2017-07-11 10:48 UTC, eed3si9n commented
@Duhemm 

> IvyConfiguration uses a logger, do we really need to give another one to retrieve? Can't it use the logger of its LibraryManagement instance? Does IvyConfiguration really need a logger?

We need logger during the setup. Task logging needs to be split for `last` to work etc.

> Both IvyPaths and IvyConfiguration need a baseDirectory. Couldn't they share the same? Fixed in #128

IvyPaths is used throughout testing, and I actually think it's a good idea to change them both at the same time, so I am keeping this one. I did move baseDirectory to external, so there are not duplicates.

> We can get default resolvers using Resolver.withDefaultResolvers. I think that we should drop the with from the name. Fixed in #128

I don't think `defaultResolvers` is good since it's returning more than the default.
`combineDefaultResolvers`? (since we can't say for sure if it's prepend or append)

> Why do we need `resolvers` and `otherResolvers`?

See Keys.scala.

>   val otherResolvers = TaskKey[Seq[Resolver]]("other-resolvers", "Resolvers not included in the main resolver chain, such as those in module configurations.", CSetting)

> Resolver.withDefaultResolvers returns a Seq, but InlineIvyConfiguration wants a Vector. Fixed in #128

We should use Vector.

> Why isn't there a way to set the configuration on an instance of ModuleDescriptor?

Not sure what you mean by this. You pass in the list of configurations to InlineConfigurations.

>  def moduleDescriptor takes a Vector[Configuration], but ModuleID takes Option[String].

I think this fine. The module descriptor has the authoritative list of configurations that it defines. ModuleID can have complex expressions like `"test->test"`.

2017-07-11 12:55 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 13:58 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 17:43 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 20:51 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 22:43 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-11 22:48 UTC, eed3si9n commented
Rebased and squashed.

Here's demo a code:

```scala
scala> import java.io.File
import java.io.File

scala> import sbt.librarymanagement._, syntax._
import sbt.librarymanagement._
import syntax._

scala> val log = sbt.util.LogExchange.logger("test")
log: sbt.internal.util.ManagedLogger = sbt.internal.util.ManagedLogger@c439b0f

scala> val lm = {
         import sbt.librarymanagement.ivy._
         val ivyConfig = InlineIvyConfiguration().withLog(log)
         IvyLibraryManagement(ivyConfig)
       }
lm: sbt.librarymanagement.LibraryManagement = sbt.librarymanagement.ivy.IvyLibraryManagement@11c07acb

scala> val module = "commons-io" % "commons-io" % "2.5"
module: sbt.librarymanagement.ModuleID = commons-io:commons-io:2.5

scala> lm.retrieve(module, scalaModuleInfo = None, new File("target"), log)
res0: Either[sbt.librarymanagement.UnresolvedWarning,Vector[java.io.File]] =
  Right(Vector(target/jars/commons-io/commons-io/commons-io-2.5.jar,
    target/jars/commons-io/commons-io/commons-io-2.5.jar,
    target/jars/commons-io/commons-io/commons-io-2.5.jar))
```

2017-07-12 09:09 UTC, Duhemm commented
Very nice. I think that we now have a much better story in terms of user API.

If you think the change is worth it, this commit: https://github.com/Duhemm/librarymanagement/commit/460d4d766acacfcb763a89646129b349f5315863 changes the configurations in `ModuleID` to be a `Vector[String]` rather than `Option[String]`. The tests pass, but I admit that I am not 100% confident about this change as it is now. I may very well have broken lots of other things. If you think that this is an improvement, I'd be happy to work a bit more on it and making sure that I didn't break something.

I'll update my WIP PR to port Zinc to this new API, this will give us a new datapoint to assess the quality of this API.

2017-07-12 10:00 UTC, dwijnand commented
@Duhemm I like what you've done - I've always been in favour of a more typed way to define module configurations. But I think in addition to splitting the string into a seq we should type the elements, i.e not have them as strings such as "compile" and "test->test".

Also, what's the thinking behind using a `Vector("compile")` default over empty vector?

2017-07-12 10:09 UTC, eed3si9n commented
@Duhemm This PR should be refactoring, so the fact that the expected value on the specs are changing makes me a bit suspicious. Also `String` represents full expression such as `runtime->*;test->default(compile)` (see http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html), so I think `Option[String]` is fine for now.

2017-07-12 10:31 UTC, dwijnand submitted a review, later dismissed

2017-07-12 10:31 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/DependencyBuilders.scala
> +      nonEmpty(name, "Artifact ID")
"Name"

2017-07-12 10:31 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +abstract class LibraryManagement extends LibraryManagementInterface {
(Forwarding my review of #123) Please could we define two different entities and use composition over inheritance?

2017-07-12 10:31 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementSyntax.scala
> +abstract class LibraryManagementSyntax extends DependencyBuilders {
Could this stay as a trait please? So it can be a mixin.

2017-07-12 10:31 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala
> +// import org.apache.ivy.plugins.resolver.DependencyResolver
commented code

2017-07-12 10:31 UTC, dwijnand commented on ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala
> +          case x :: (xs @ _)                           => x
what's going on here?

2017-07-12 10:31 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/VersionNumber.scala
> +            case (x1 @ _, y1 @ _, 0, ts1, x2 @ _, y2 @ _, 0, ts2)
what with all the `@ _`?

2017-07-12 10:31 UTC, dwijnand commented on ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala
> +      if (configuration.publishMavenStyle) None
Isn't this a blocker for this PR? Does this (with the todo above) mean we no longer publish POM files?

2017-07-12 10:31 UTC, dwijnand commented on ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala
> +    def applyFilter(f: ArtifactTypeFilter, a: IArtifact): Boolean =
The f is redundant.

2017-07-12 10:31 UTC, dwijnand commented on ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala
> +          val ur = JsonUtil.parseUpdateReport( /* md, */ path, cachedDescriptor, log)
commented code

2017-07-12 10:57 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementSyntax.scala
> +abstract class LibraryManagementSyntax extends DependencyBuilders {
Is it really worth it? The trait-to-interface is still somewhat fragile (e.g. `val` must be final without return types), and I don't know who would ever need to mix this in.

2017-07-12 10:57 UTC, Duhemm commented on ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala
> +          case x :: (xs @ _)                           => x
I think that's to silent the huge number of warnings. If I'm right, I would prefer `case x :: _ => ...`

2017-07-12 10:58 UTC, eed3si9n commented on ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala
> +          case x :: (xs @ _)                           => x
Avoiding the compiler warning. Could also be `_`, but I grew up writing `x :: xs`.

2017-07-12 11:00 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/VersionNumber.scala
> +            case (x1 @ _, y1 @ _, 0, ts1, x2 @ _, y2 @ _, 0, ts2)
Avoiding compiler warnings.

2017-07-12 11:03 UTC, eed3si9n commented on ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala
> +      if (configuration.publishMavenStyle) None
This is the first step towards folding `deliver` into `publish`.
I haven't changed anything with POM. I think it's handled as an artifact in Defaults.scala:

```scala
    publishArtifact in makePom := publishMavenStyle.value && publishArtifact.value,
    artifact in makePom := Artifact.pom(moduleName.value),
```

2017-07-12 11:04 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/LibraryManagement.scala
> +abstract class LibraryManagement extends LibraryManagementInterface {
Yes. Sorry about that.

2017-07-12 11:05 UTC, Duhemm commented
@dwijnand I'm not super familiar with this code, but my understanding is that when there is no configuration that is explicitly set (`None`), it means `compile`. Similarly, here an empty vector means `compile`.

@eed3si9n I agree, this is just a POC. I changed the tests to compensate for the `:compile` that is always shown. Previously, we wouldn't show it if it was `None` (which implicitly means `compile`).

2017-07-12 11:16 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementSyntax.scala
> +abstract class LibraryManagementSyntax extends DependencyBuilders {
We need it https://github.com/sbt/sbt/blob/1.0.x/sbt/src/main/scala/package.scala#L11

2017-07-12 11:20 UTC, dwijnand commented on ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala
> +          case x :: (xs @ _)                           => x
TIL. Thank you.

2017-07-12 11:23 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementSyntax.scala
> +abstract class LibraryManagementSyntax extends DependencyBuilders {
ok. I guess I'll turn them into traits and put comments to remind future developers to use final val.

2017-07-12 11:48 UTC, Duhemm commented
`InlineConfiguration` does not follow the builder pattern. Is that on purpose?

2017-07-12 11:52 UTC, eed3si9n commented
@Duhemm 

Yes. There's a weird coupling between `module: ModuleID` and `moduleInfo: ModuleInfo`. Hopefully it's not a big deal since there are some helper functions in LibraryManagement to define one.

2017-07-12 12:02 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-12 12:16 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +abstract class LibraryManagementInterface {
Could the interfaces in this file be interfaces?

Also can we call this RetrieverInterface (or similar)?

2017-07-12 12:23 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +abstract class LibraryManagementInterface {
retrieve is a specific feature so a generic sounding name would be `DependencyResolutionInterface`.

2017-07-12 12:29 UTC, dwijnand commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +abstract class LibraryManagementInterface {
WFM

2017-07-12 12:33 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-12 12:33 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +abstract class LibraryManagementInterface {
Done.

2017-07-12 13:25 UTC, dwijnand commented
LGTM, pending sbt/zinc and sbt/sbt ripple PRs.

2017-07-12 13:28 UTC, Duhemm requested changes
See comment

2017-07-12 13:28 UTC, Duhemm commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +}
Could you please split this in 3 files (`DependencyResolutionInterface.scala`, `PublisherInterface.scala` and `ModuleDescriptor.scala`)?

2017-07-12 14:31 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/LibraryManagementInterface.scala
> +}
I actually thought it would be a good idea to keep all the open-ended interfaces so we can link to the file and talk about it.

2017-07-13 07:02 UTC, Duhemm submitted a review, later dismissed

2017-07-13 08:47 UTC, Duhemm commented
I forgot about `transitiveScratch`, it's still part of this API. Do we really want it there? Could we get documentation?

2017-07-14 20:21 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-15 16:06 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-15 16:08 UTC, eed3si9n commented
@Duhemm noticed that MakePomConfiguration was plain class, so I added https://github.com/sbt/librarymanagement/pull/124/commits/a09af23cc654a4de15eb9b53155e5a61b92f6f42. This is also rebased on config fix that exposes `Configuration.of(..)`.

2017-07-15 17:52 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?librarymanagement=pull/124/head&deploy_to_bintray=false">this link.</A>

2017-07-15 18:07 UTC, eed3si9n commented
Tests passing and `transitiveScratch` was ripped out, so I think this is good to go!

2017-07-15 18:07 UTC, merged