Adds null check for 'sbt.managedChecksums' in ivySettings fixing #195
sbt/librarymanagement pull request #197
Opened 2018-01-09 22:34 UTC by IanGabes

Sorry for the messy diff. I chose to leave all of the changes in, as most of the newline spacing was performed by scalafmt. If the maintainer wishes, I can fix this.

This PR adds a simple null check to protect against `"null"` from being parsed as a boolean.

Thanks for your time!

2018-01-09 22:34 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?librarymanagement=pull/197/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2018-01-10 03:26 UTC, eed3si9n requested changes

2018-01-10 03:26 UTC, eed3si9n commented on ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala
> +    val testerino = "PLEASE LOL "
Could you remove this?

2018-01-18 19:37 UTC, eed3si9n commented
Also if this is a bug fix, we should target 1.1.x branch.

2018-03-18 08:11 UTC, eed3si9n commented
Closing this in favor of https://github.com/sbt/librarymanagement/pull/228

2018-03-18 08:11 UTC, closed without merging