Fix CrossVersion.Disabled compat
sbt/librarymanagement pull request #280
Opened 2018-11-21 16:25 UTC by dwijnand

2018-11-22 17:25 UTC, dwijnand commented
Need to add MiMa exclusions for these.  I doubt anyone's used them seeing how they're wrong, but also they're inlined constants, so even if they're binary API has changed there are no call sites in bytecode because the values got inlined.

2018-11-23 15:44 UTC, dwijnand commented
Reported the false positive in MiMa: https://github.com/lightbend/migration-manager/issues/266

2018-11-23 21:31 UTC, dwijnand commented
@eed3si9n WDYT?

2018-11-24 04:48 UTC, eed3si9n requested changes
Currently the final vals are pointing to the companion objects, and I think we should encourage ppl to use the lowercase versions like `full` and `binary` in sbt 0.13.
The only odd duck is `Disabled`, which was an object in sbt 0.13, so if you want to make this change for better source compat, I think we should limit it to `Disabled`.

Also could we target `develop` branch first?

2018-11-24 04:48 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/CrossVersionExtra.scala
> +  final val Disabled = sbt.librarymanagement.Disabled()
The corresponding construct in sbt 0.13 https://github.com/sbt/sbt-zero-thirteen/blob/v0.13.17/ivy/src/main/scala/sbt/CrossVersion.scala#L19:

```scala
  object Disabled extends CrossVersion { override def toString = "disabled" }
```

so the above change could be considered valid for source compat with sbt 0.13, but in general we probably should recommend migrating to lowercase `CrossVersion.disabled`.

2018-11-24 04:48 UTC, eed3si9n commented on core/src/main/scala/sbt/librarymanagement/CrossVersionExtra.scala
> +  final val Binary = sbt.librarymanagement.Binary()
Binary and Full were classes in sbt 0.13, but had lower case value `binary` and `full`.
So keeping `Binary` as the companion object of `sbt.librarymanagement.Binary` kind of makes sense to me.

2018-11-24 09:33 UTC, dwijnand commented
Yep `CrossVersion.Disabled` was what lead me to this change, so I'm happy to restrict this PR to just that.  Also, it's needn't be on the bugfix highway, so I'm happy to re-target it to develop.

2018-11-25 04:50 UTC, eed3si9n approved these changes
Thanks @dwijnand

2018-11-25 04:51 UTC, merged

2019-01-22 12:54 UTC, eed3si9n commented
@dwijnand We might need to revert this PR since @cunei found breakage in the community build:

```
[cats] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;
[cats-effect] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;
[circe] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;
[coursier] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;
[scalacheck] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;
[scalaz] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;
```

2019-01-22 13:28 UTC, dwijnand commented
It's a false positive because it's a folded constant.

But MiMa isn't aware of those... https://github.com/lightbend/migration-manager/issues/266

2019-01-22 13:29 UTC, dwijnand commented on build.sbt
> +      // there are no call sites in bytecode because the value got inlined
More precisely "constant folded" not "inlined".

2019-01-22 13:51 UTC, eed3si9n commented
@cunei Do you have a stacktrace? I am guessing some plugin out there is actually calling `Disabled()`.

2019-01-22 13:55 UTC, dwijnand commented
True, it must be.  Going to ask the Scala team about constant folding.

2019-01-22 15:27 UTC, eed3si9n commented
I wonder if we can keep the bincompat by adding `def apply() = this`.

2019-01-22 16:15 UTC, dwijnand commented
Yeah, I wondered that too, but there's no `apply` in those java method signatures.

2019-01-22 16:37 UTC, eed3si9n commented
ok so `Disabled` is the name of the static method on `CrossVersion$` class.

2019-01-22 16:38 UTC, eed3si9n commented
Change `val` to `def`?

2019-01-22 16:47 UTC, eed3si9n commented
https://github.com/sbt/librarymanagement/pull/290