Flip the default to not use Gigahorse by default
sbt/librarymanagement pull request #317
Opened 2019-08-27 22:27 UTC by eed3si9n

Fixes sbt/sbt#3570

The primary motivation for bringing in Gigahorse was to speed up the dependency resolution, especially in a high-latency environment like Australia, by enabling keep-alive. One of unintended consequences was that it ended up exposing either a bug in okhttp or Nexus / Artifactory's handling of keep-alive, since corporate users behind these proxy repositories started to experience problem publishing. Multiple people have also reported that putting network proxies like HAProxy works around this issue, which seems consistent with the theory.

Now that dependency resolution has switched to using Coursier by default, I am just going to flip the default here so publishing would use Ivy's default URL handler based on `java.net.HttpURLConnection` - https://github.com/sbt/ivy/blob/5681e1a77a149b93a4cfbe4a86d0263d7bd223eb/src/java/org/apache/ivy/util/url/BasicURLHandler.java

2019-08-27 22:38 UTC, eatkins requested changes
Even though I know that things have worked ok without the try/catch, I've seen this kind of parsing cause some projects to crash (play did something similar in ~run which made it impossible to test a snapshot version of sbt).

Otherwise looks good.

2019-08-27 22:38 UTC, eatkins commented on core/src/main/scala/sbt/internal/librarymanagement/LMSysProp.scala
> +    val version = sys.props("java.specification.version").split("\\.").toList.map(_.toInt)
This should probably be in a try catch in case the property is somehow null or if there are strings in the java version (unlikely but someone could be testing with an experimental jvm).

2019-08-27 22:38 UTC, eatkins commented on core/src/main/scala/sbt/internal/librarymanagement/LMSysProp.scala
> +  def modifyVersionRange: Boolean = getOrTrue("sbt.modversionrange")
Why is this a def but the others are vals?

2019-08-28 03:34 UTC, eed3si9n commented on core/src/main/scala/sbt/internal/librarymanagement/LMSysProp.scala
> +  def modifyVersionRange: Boolean = getOrTrue("sbt.modversionrange")
I guess I can make it a lazy val. The one above is plain `val` because it gets used in resolver initialization on vals.

```scala
  val TypesafeRepositoryRoot = typesafeRepositoryRoot(useSecureResolvers)
```

2019-08-28 03:41 UTC, eatkins approved these changes
LGTM

2019-08-28 08:31 UTC, avdv commented on core/src/main/scala/sbt/internal/librarymanagement/LMSysProp.scala
> + * Copyright 2011 - 2018, Lightbend, Inc.
Maybe update the year to 2019 here?

2019-08-28 13:25 UTC, eed3si9n commented on core/src/main/scala/sbt/internal/librarymanagement/LMSysProp.scala
> + * Copyright 2011 - 2018, Lightbend, Inc.
I'll get around to it when I add sbt-header.

2019-08-28 13:25 UTC, merged