Expose RichUpdateReport & DependencyFilter
sbt/librarymanagement pull request #78
Opened 2017-03-31 17:08 UTC by dwijnand

Fixes #42

2017-03-31 17:31 UTC, eed3si9n requested changes

2017-03-31 17:31 UTC, eed3si9n commented on librarymanagement/src/main/scala/sbt/librarymanagement/RichUpdateReport.scala
> +    configuration: ConfigurationFilter = configurationFilter(),
I think we should avoid default args.

2017-03-31 20:09 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/RichUpdateReport.scala
> +    configuration: ConfigurationFilter = configurationFilter(),
Is overloading ok? 3 versions with (undefaulted) ConfigurationFilter, ModuleFilter and ArtifactFilter?

My motivation is (attempts at) source-compatibility with 0.13.

2017-03-31 20:12 UTC, dwijnand commented on librarymanagement/src/main/scala/sbt/librarymanagement/RichUpdateReport.scala
> +    configuration: ConfigurationFilter = configurationFilter(),
+1 version with all 3 undefaulted too. That would cover the 3 use-cases I see in Scala.js.

2017-04-01 03:57 UTC, eed3si9n commented on librarymanagement/src/main/scala/sbt/librarymanagement/RichUpdateReport.scala
> +    configuration: ConfigurationFilter = configurationFilter(),
Yea. Overloading is fine.

2017-04-04 05:02 UTC, eed3si9n approved these changes

2017-04-04 05:02 UTC, merged