Reformat with scalafmt
sbt/librarymanagement pull request #87
Opened 2017-04-25 09:43 UTC by jvican

Same as https://github.com/sbt/sbt/pull/3125.

2017-04-25 09:58 UTC, dwijnand requested changes

2017-04-25 09:58 UTC, dwijnand commented on build.sbt
> +    commands += Command.command("scalafmtCheck") { state =>
you need to add this to the root (lmRoot)

2017-04-25 11:08 UTC, jvican commented on build.sbt
> +    commands += Command.command("scalafmtCheck") { state =>
Done.

2017-04-26 21:02 UTC, jvican commented
I have updated the formatting of all the sources here. Right now, we strictly follow what upstream sbt does. Do you mind having a look @eed3si9n ?

2017-04-26 21:03 UTC, eed3si9n approved these changes

2017-04-26 21:04 UTC, eed3si9n commented
LGTM

2017-04-26 21:38 UTC, jvican commented
Since this is just a port of sbt/sbt reformatting, there's already a signoff and CI is green, can we merge this and I rebase https://github.com/sbt/librarymanagement/pull/88?

2017-04-26 21:43 UTC, merged