Allow to define concrete resolvers for dependencies
sbt/librarymanagement pull request #97
Opened 2017-05-11 14:09 UTC by jvican

This depends on https://github.com/sbt/librarymanagement/pull/96/files.
    
Sometimes, for predictability and performance, we may be interested in
specifying the concrete resolver that a `ModuleID` should use.

This patch achieves this by adding a new field to `UpdateOptions` and
then getting this information from the `SbtChainResolver`, that will
select the concrete resolver for a given dependency descriptor.

Why is this useful? Well, two reasons:

* Predictable behaviour. We have the guarantee that an artifact only
  comes from a concrete resolver.
* Resolution speedup. Around 1/3 or 1/2 times faster than normal
  resolution in a moderate test case scenario. If there is a lot of
  latency or network connection is poor, speedups will be higher.

Some results of tests I have just ran:

```
NORMAL RESOLUTION TIME 1790
FASTER RESOLUTION TIME 1054
```

```
NORMAL RESOLUTION TIME 2078
FASTER RESOLUTION TIME 1055
```

Lots of projects can benefit from this option, as well as organizations
and companies. This will eventually integrate with the dependency lock
file, but can be used independently of it.

2017-05-12 16:53 UTC, jvican commented
This has been rebased and is ready for review.

2017-05-12 18:10 UTC, jvican commented
Tests are green.

2017-05-12 18:11 UTC, jvican commented on librarymanagement/src/main/scala/sbt/internal/librarymanagement/Ivy.scala
> +  // TODO: Expose the changing semantics to the caller so that users can specify a regex
I have followed up with: https://github.com/sbt/librarymanagement/issues/101.

2017-05-12 20:17 UTC, eed3si9n requested changes
Looks good overall.
Minor comments.

2017-05-12 20:17 UTC, eed3si9n commented on librarymanagement/src/main/scala/sbt/librarymanagement/UpdateOptions.scala
> +      moduleResolvers: Map[ModuleID, Resolver] = this.moduleResolvers
moduleResolvers should be added to equals and hashCode.

2017-05-12 20:17 UTC, eed3si9n commented on librarymanagement/src/main/scala/sbt/librarymanagement/UpdateOptions.scala
> +    val moduleResolvers: Map[ModuleID, Resolver]
Should this be an immutable Map?

2017-05-12 20:20 UTC, jvican commented on librarymanagement/src/main/scala/sbt/librarymanagement/UpdateOptions.scala
> +      moduleResolvers: Map[ModuleID, Resolver] = this.moduleResolvers
This is a very good catch.

2017-05-12 20:21 UTC, jvican commented on librarymanagement/src/main/scala/sbt/librarymanagement/UpdateOptions.scala
> +    val moduleResolvers: Map[ModuleID, Resolver]
Yes, it should be immutable. We don't transform it internally and we don't want their contents to be exposed and modified from the outside. We just use it to represent some data that we use once inside sbt' chain resolver.

2017-05-12 20:22 UTC, jvican commented
Speedup is 3x in CI.
```
NORMAL RESOLUTION TIME 960

FASTER RESOLUTION TIME 361
```

2017-05-12 21:59 UTC, jvican commented
I just fixed the remaining bit. PR is green.

2017-05-13 02:57 UTC, eed3si9n approved these changes

2017-05-13 02:57 UTC, merged